var newsArray;

function updateNewsArray() {
newsArray = [//always true 
["The cookie is a lie.", true, "a1"], 
["Antimatter cookies have been confirmed to not exist, whoever claims that, stop.", true, "a2"], 
["Antimatter ghosts do not exist. Just like matter ghosts. They don't have any matter, for that matter.", true, "a3"],
["Nuclear power plants have been abandoned in favor of antimatter power.", true, "a4"],
["Antimatter prices have drastically dropped due to newfound abundance.", true, "a5"], 
["In the news today, humans make an antimatter animal sacrifice to the antimatter god.", true, "a6"], 
["You made one antimatter! Whatever that means.", true, "a7"],
["Scientists confirm that the colour of antimatter is Blurple", true, "a11"], 
["How does it matter if its antimatter?", true, "a10"], 
["None of this matters", true, "a9"], 
["IN THE END, IT DOESN'T ANTIMATTER -hevipelle", true, "a8"],
["How does NASA organise a party? They planet.", true, "a12"], 
["Electrons are now seeing the happy things in life. We're calling these happy electrons 'Positrons.' Wait, that's taken?", true, "a13"],
["This completely useless sentence will get you nowhere and you know it. What a horrible obnoxious man would come up with it, he will probably go to hell, and why would the developer even implement it? Even if you kept reading it you wouldn't be able to finish it (the first time).", true, "a14"],
["GHOST SAYS HELLO -Boo-chan", true, "a15"], 
["Can someone tell hevi to calm down? -Mee6", true, "a16"], 
["Due to Antimatter messing with physics, a creature that was once a moose is now a human", true, "a17"], 
["!hi", true, "a18"],
["Alright -Alright", true, "a19"], 
["The English greeting is not present in Antimatter speak.", true, "a20"], 
["To buy max or not to buy max, that is the question", true, "a21"], 
["This antimatter triggers me", true, "a22"],
["No, mom, I can't pause this game.", true, "a23"], 
["Scientific notation has entered the battlefield.", true, "a24"], 
["Make the Universe Great Again! -Tronald Dump", true, "a25"], 
["#dank-maymays", true, "a26"],
["A new religion has been created, and it's spreading like wildfire. The believers of this religion worship the Heavenly Pelle, the goddess of antimatter. They also believe that 10^308 is infinite.", true, "a27"], 
["Someone has just touched a blob, and blown up. Was the blob antimatter, or was the guy made of Explodium?", true, "a28"],
["If you are not playing on Kongregate or ivark.github.io, the site is bootleg.", true, "a29"], 
["Rate 5 on Kongregate so more people can experience this 5 star Rating", true, "a30"], 
["BOO!", true, "a31"], 
["You ate for too long. -hevipelle", true, "a32"], 
["I hate myself. -Boo-chan", true, "a33"],
["Gee golly -Xandawesome", true, "a34"], 
["Above us, there is nothing above, But the stars, above.", true, "a35"], 
["If black lives matter, do white lives antimatter?", true, "a36"], 
["Somebody wasn't nice, he got an antimatter-storm.", true, "a37"],
["You are living, you occupy space, you have a mass, you matter... unless you antimatter.", true, "a38"], 
["I clicked too fast... my PC is now dematerialised.", true, "a39"],
["If an alien lands on your front lawn and extends an appendage as a gesture of greeting, before you get friendly, toss it an eightball. If the appendage explodes, then the alien was probably made of antimatter. If not, then you can proceed to take it to your leader. -Neil deGrasse Tyson", true, "a40"],
["There always must be equal matter than there is antimatter, I guess your mom balances that a bit", true, "a41"], 
["Nothing is created, nothing is destroyed.", true, "a42"], 
["We dug a big hole to store this antimatter... Adele's rolling in it.", true, "a43"],
["If everything is antimatter, how can you see yourself?", true, "a44"], 
["The stock markets have crashed due to antimatter beings somehow knowing what they will be tomorrow.", true, "a45"], 
["My dog ate too much antimatter, now he is doing 'meow!'", true, "a46"], 
["If you put infinity into your calculator it will result in 42!", true, "a47"],
["You have found the rarest antimatter pepe, it's ultra rare!", true, "a48"], 
["Can we get 1e169 likes on this video??? Smash that like button!!", true, "a49"],
["The smell of antimatter has been revealed. It smells like kittens", true, "a50"], 
["Just another antimatter in the wall", true, "a51"], 
["GET SNIPED, WEAKLING", true, "a52"], 
["Thanks a lot -dankesehr", true, "a53"],
["This world situation is a SOS situation to the world!! MAYDAY, MAYDAY!!", true, "a54"], 
["As for sure as the sun rises in the west, of all the singers and poets on earth, I am the bestest. - hevipelle", true, "a55"], 
["I'm good at using github -hevipelle", true, "a56"],
["A new chat server has been created for Antimatter people to spy on Matter people, and the world has fallen into chaos and discord", true, "a57"], 
["A new study has come out linking the consumption of potatoes with increased risk of Antimatter implosion.  Scientists suggest eating more.", true, "a58"], 
["I thought that I fixed that bug but apparently some update broke it again -hevipelle", true, "a59"],
["Maybe I'm gay then -Bootato", true, "a60"], 
["Breaking news! Hevipelle has just announced that the buy max button is in fact going to be removed!", true, "a61"], 
["I dedicate this game to my YouTube subscribers", true, "a62"],
["Antimatter guns don't kill antimatter people, antimatter people kill antimatter people but does that mean that antimatter toaster doesn't toast antimatter toasts, antimatter toast toasts antimatter toasts?", true, "a63"],
["But to an antimatter person, wouldn't they be matter and us antimatter?", true, "a64"], 
["And nothing Antimatters", true, "a65"],
["School starting up strikes fear in students universe-wide, as schools are no longer segregated between Matter and antimatter. Annihilation is prominent.", true, "a66"],
["Why does no one talk about the 0th dimension?", true, "a67"], 
["The fatter catter satter on the antimatter.", true, "a68"], 
["Who let the DOgs out?", true, "a69"], 
["If you can't read this you disabled the news.", true, "a70"],
["Doesn't leave, just mutes the server so he doesn't receive notifications", true, "a71"], 
["Most quotes found online are falsely atributed -Abraham Lincoln", true, "a72"], 
["It should work now, but it doesn't -hevipelle", true, "a73"],
["This game doesn't have any errors... they're alternative successes.", true, "a74"], 
["A third type of matter has been discovered: null matter. It doesn't do anything and is basically useless. The scientists who discovered it were fired.", true, "a75"],
["Your Mother-in-Law keeps nagging you about all these antimatter colliders.", true, "a76"], 
["If matter exists, then does antimatter not exist?", true, "a77"], 
["Antimatter=Life. Not cobblestone, not dirt, nothing like that. Antimatter.", true, "a78"],
["Breaking News: Error Error Error", true, "a79"], 
["How much antiwood could an antiwoodchuck chuck if an antiwoodchuck could chuck antiwood?", true, "a80"], 
["Chaos isnt a pit, chaos is a matter", true, "a81"],
["That's because I'm a good game developer and pushed some code that totally works -hevipelle", true, "a82"], 
["What's the matter with anti matter?", true, "a83"],
["Doesn't it annoy you when people don't finish their", true, "a84"], 
["Don't anti-quote me on this", true, "a85"], 
["Antimatter is honest, matter makes up everything", true, "a86"],
["According to no known laws of aviation, there are multiple ways a bee should be able to be swallowed up by antimatter", true, "a87"], 
["You either die as matter or live long enough to be consumed by the antimatter, and then die again", true, "a88"],
["If you gaze long enough into the antimatter, the antimatter gazes back into you", true, "a89"], 
["Always gonna give you up. Always gonna let you down. - anti-Rick Astley", true, "a90"],
["Antimatter Dimensions: the next update is always 5 hours away. Always.", true, "a91"], 
["#DimensionLivesAntimatter", true, "a92"],
["Do antimatter people with suicidal thoughts get depressants?", true, "a93"], 
["To matter or to antimatter, that is the question.", true, "a94"], 
["Why is everything so Hevi?",  true, "a95"],
["It has been scientifically proven ages ago, that cats made of matter are cancer. We have good news, because cats made of antimatter are still cancer",  true, "a96"],
["Nobody once told me the anti-world wasn’t gonna roll me", true, "a97"], 
["Antimatter is like internet. If you're reading this, you can't have enough of it.",  true, "a98"],
["Antimatter has made time travel possible and I'm here to make the past great again. - 2nd President of the World",  true, "a99"],
["Please insert Disc -1 to continue playing  Antimatter Dimensions ™.", true, "a100"], 
["Lore - coming soon ™", true, "a139"],
["I was a part of antimatter like you once. But then I got matter in my knee.", true, "a101"], 
["Antimatter... antimatter never changes... until you get to quantum physics of antimatter, but we don't have enough tachyon particles for that.", true, "a102"],
["There is no war in Antimatter Dimensions. Here we are safe. Here we are free.", true, "a103"], 
["Antimatter has solved global warming.  In unrelated news, the Earth no longer exists.",  true, "a104"],
["Anti-water, anti-Earth, anti-fire, anti-air. Long ago, the four anti-nations lived together in harmony. Then, everything changed when the anti-Fire Nation attacked. Only the anti-Avatar, the master of all 4 anti-elements could bring balance to the anti-world, but when the world needed him most, he accidentally touched some regular matter and exploded.",  true, "a105"],
["If you open an anti-lootbox, are you selling random possessions for in-game currency?", true, "a106"], 
["People are beginning to question Hevipelle's existence.",  true, "a107"], 
["Antimatter Dimensions is proud to be sponsored by Lehmä! Now offering - grass eating lessons! Learn what grass is safe to eat and what grass isn't.",  true, "a108"],
["It is the year 2422. The update still isn't out. Hevi is working on balancing unfunity dimension dimensions and challenges for the 38th layer of prestige. There are over 100 rows of achievements. They're getting ready to start using breaking_breaking_breaking_infinity.js", true, "a109"],
["Import Christmas for a secret theme                           wait, you can't import anything trololololol", true, "a110"],
["What the frick did you just freaking say about me, you little snot? I’ll have you know I graduated top of my class in the Antimatter Seals, and I’ve been involved in numerous secret raids on the 9th Dimension, and I have over 300 NNnNeMI-NNnNe confirmed kills. I am trained in potato warfare and I’m the top sniper in the entire Antimatter Galactic armed forces. You are nothing to me but just another infinity. I will wipe you the frick out with Max All mashing the likes of which has never been seen before in this dimension, mark my freaking words. You think you can get away with saying that crap to me over the Interdimensional network? Think again, idiot. As we speak I am contacting my secret network of autobuyers across the galaxy and your IP is being traced right now so you better prepare for the Big Crunch, maggot. The Big Crunch that wipes out the pathetic little thing you call your life. You’re freaking dead, kid. I can be anywhere, anytime, and I can kill you in over seven 😠💩 different ways, and that’s just with my mouse. Not only am I extensively trained in dimension shift combat, but I have access to the entire arsenal of the Antimatter Marine Corps and I will use it to its full extent to wipe your miserable butt off the face of the universe, you little crap. If only you could have known what unsprucy retribution your little “clever” comment was about to bring down upon you, maybe you would have held your freaking tongue. But you couldn’t, you didn’t, and now you’re buying singles, you goddamn idiot. I will crap antimatter crap all over you and you will drown in it. You’re freaking dead, kiddo.", true, "a111"],
["(Make me sleep) Put me to sleep inside. (I can't sleep) Put me to sleep inside. (Leave me) Whisper my name and give me to the dark. (Make me sleep) Bid my milk to stay. (I can't fall asleep) Before I become done. (Leave me) Leave me to the nothing I've become.", true, "a113"],
["A preview of the next update - loot boxes! Feel a sense of pride and progression as you open cosmic, galactic, and universal lootboxes for chances at rare skins, unique challenges with uniquer rewards, time skips and even new dimensions!", true, "a114"],
["The intent of dimensions is to give a sense of pride and accomplishment", true, "a115"],
["Refreshing cures cancer", true, "a116"],
["I have a 9th, i have a dimension... UHH... IT DOESN'T EXIST!", true, "a117"],
["Since when did we start reporting stuff like this? Half of it isn't even proper news, it's just jokes and meta-references, it doesn't even make sens-HAHAHA DISREGARD THAT I SUCK CO-", true, "a118"],
["The year is 1944, Hevipelle can't release updates for AD because he doesn't exist", true, "a119"],
['"THAT DIMENSION DOESN\'T EXIST" -GhostBot', true, "a120"],
["Most things you know as nuts are actually Drupe seeds or Legumes. Hevipelle on the other hand is quite crazy and can thus be considered a dry uncompartmented fruit.", true, "a121"],
//[eval('LZString.decompressFromEncodedURIComponent("GISwdgNghmAmAEsCmBjaAnJBneAXAFlLvCLgOQ5a5Tq7gDmeA9iQLYAOTt8AwjCknRA")'), true, "a122"],
//[eval('LZString.decompressFromEncodedURIComponent("IIGxAIBcAsEsGdywLYAcD2AnSsB2BzJRZAQwGs9DkBTcAYXVwDMBXeagEyA")'), true, "a123"],
["Only today you can call 1-800-ANTIMATTER and get a FREE Infinity Dimension! The package also comes with a COMPLETELY FREE SHIPPING and a FREE HIGH DEFINITION ANTI-V!!! Only today for the low price of 42! Estimated delivery time - 5 hours.", true, "a124"],
["1e420 blaze it.", true, "a125"],
["This game doesn't have any bugs, you're just doing it wrong.", true, "a126"],
["Antimatter_Dimensions.mp1.79e308", true, "a127"],
["https://www.youtube.com/watch?v=dQw4w9WgXcQ", true, "a128"],
["Click this to unlock a secret achievement.", true, "a129"],
["Warning - We have just been informed that there is a chance of infection with a mind-virus of the Basilisk type, similar to the infamous winking parrot. This particular example is known as 'Fractal Cancer Type III'. This is believed to cause a 'crashing' of the mind, similar to a computer crash, due to the mathematical complexity of the image causing mathematical ideas that the mind can't comprehend, a Gondelian shock input eventually leading to crashing through Gondelian spoilers. All who have researched it have eventually died the same way, so it is impossible to tell exactly, but this is the common belief. Regardless, with the introduction of 'cancer' mode, as well as reports of it's spontaneous appearance, sufficient repetition of this mode's appearance may lead to  an image forming in the mind similar to 'Fractal Cancer Type III'. With this in mind, we have some suggestions if you find yourself plagued with it. First, refresh immediately and see if that fixes the issue. If not, navigate to options, and change the theme from cancer to literally anything else. And above all else, Godspeed. We can't afford to lose anymore viewers.", true, "a130"],
["If I have bad English, I'll study English until I have good English.", true, "a131"],
["Someone once told me that antimatter is gonna roll me. I ain't the sharpest atom in the shed. WELL, the tubes start coming and they don't stop coming...", true, "a132"],
['Because of this game I can now use the word "infinity" as a verb.', true, "a133"],
["Ahhh i love the smell of particle annihilation in the morning", true, "a134"],
["The person who said ghosts don't exist obviously doesn't have a discord", true, "a135"],
["AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAntimatter Dimensions was made by some dude from Finland", true, "a136"],
['The Holy trinity of Hevipelle, Antimatter, Infinity Points, and Eternity Points. These 3 resources let us access Hevi’s gift, Time Theorems. And with these Time Theorems, we reach out to Hevi, and call, “Hevi, bless us on this fine day!” And Hevi does. He give us the blessing of Time Studies. These Time Studies were blessings so powerful, Hevi restricted their power. He said, “ I will give you a choice of three paths” and then humanity chose. The short, cheap route of Normal Dimensions, giving instant gratification, the powerful choice of Infinity Dimensions, which were a fast, middle ground path, or Time Dimension, the long wait, and struggle, of humanity. Then, as humanity chose, a crack broke the earth. A serpent snaked out and sneered to humanity, “I will offer the powerful choice of a ninth dimension! I am Slabdrill, lord of all Unhevi. Humanity rose and said “ Begone Slabdrill! We want none of your foul Heresy!” And Hevi rose as well, and smote Slabdrill with his godlike power. As Slabdrill’s corpse fell into the earth, he cried “ this will not be the last of me! Hevi will betr-“ and he fell in the Abyss of matter. Hevi gifted humanity with Eternity upgrades, which boosted infinity dimensions and time dimensions. And Hevi gave humanity his greatest gift . EP multipliers. He said, these will multiply all EP gained by 5, but their cost will increase 25 times. Use them wisely. And Humanity journeyed off with their new power, as Slabdrill’s words echoed in their heads.', true, "a137"],
["We have updated our Antimatter Privacy Policy.", true, "a138"],
  
//NG+++ ones
["another aarex masterpiece ~ Spanosa", true, "am8"],
["New updates are coming in a day, not 5 hours. Sorry, jokers!", true, "am14"],
["'There is a lot of bugfixes coming, but I am too busy that I can't develop my modification a lot.' -Aarex'", true, "am23"],
["'I AM NOT AN AI!' -Aarex", true, "am24"],
["'I AM NOT AN AI!' -Aarex", true, "am25"],
["'I AM NOT AN AI!' -Aarex", true, "am26"],
["'I don't really think I am an A.I.' -Aarex", true, "am27"],
["The news ticker is already dead despite taking up a two dimensional area", true, "am29"],
["All notations are good notations. Maybe except Psi.", true, "am30"],
["Why even bother using the news ticker? Sure, there are a few funny ones, but even they get old after a while and most of them are just long strings of nonsensical text that repeat over and over until you get sick of seeing them. You've probably seen this one at least nine times already, and you're going to keep seeing it and seeing it until you finally decide to turn off the news.", true, "am31"],
["News ticker has declared dead! Provides no purpose.", true, "am32"],
['"My save broke!" ~ New player who played a challenge in late-game.', true, "am33"],
["That's how NG+++ works!", true, "am34"],
["var add ad + gamebreakingcontent ngplusthree", true, "am35"],
["'BREAKING NEWS: wAFFLE found a game-breaking bug that I have to release a new update to beat him!' -Aarex", true, "am36"],
["", true, "am37"],
["A brave man said 'When will gamers reach the singularity of this game?' But the game said 'There is insufficient data for the answer'.", true, "am45"],
["New prestige layer coming soon, Police-ize! When you prestige, you unlock officer dimensions. They behave like all other dimensions except they produce anti-anti-antimatter. This anti-anti-antimatter can be used to purchase more officer dimensions. The anti-anti-antimatter also makes your galaxies feel more safer, providing a boost in galaxy efficiency, based on your highest reached AAAM.", true, "am50"],
['"THERE WILL BE NO NG+4. NG+3 ALWAYS HAVE UPDATES." - Aarex   [NG+4 was then created by Aarex]', true, "am51"],
["You're reading news too much.", "player.newsArray.length >= 215", "am54"],
["You're addicted to news.", "player.newsArray.length >= 230", "am55"],
["Okay. You can stop reading the news.", "player.newsArray.length >= 245", "am56"],
["You know, you should really turn off the news ticker.", "player.newsArray.length >= 260", "am57"],
["People talk about this 9th dimension, but what about the 4th dimension?", true, "am59"],
["When life gives you null matter, you hold your finger down on the enter key on the 'Max all dimensions' button.", true, "am60"],
["Don't you hate when people say like if you agree? Like if you agree", true, "am61"],
["Did you know that -1% of people believe the 9th Dimension exists?", true, "am63"],
["Antimatter has been found on the Moon. And the moon also doesn't exist.", true, "am64"],
["BREAKING NEWS: Suicide rates have dropped to 0% because suicidal people have touched antimatter by accident", true, "am66"],
["nice.", true, "am69"],
["The year is 2120. Aarex is somehow still alive. However, the next update isn't out. Aarex is supposed to be working on the 8th prestige layer, but has invented approximately 72423985051 other mods and games, so he can't. Updates only come out approximately ever 5 years. (And you thought the 5 hours meme was funny.)", true, "am71"],
["Breaking News: Aarex has announced NG-9. It includes you starting with the ability to purchase IDs, ubt everything starts 1e308x slower! Estimated time to complete: 10,000 years.", true, "am72"],
["There are a lot of news tickers, how did you find this one?", true, "am73"],
["In the beginning, there was only the abyss of Matter. But then, an antimatter singularity rose and created the god Hevipelle, and he said, \"Let there be antimatter.\" And so there was. Hevipelle then said, \"Let there be Infinity Points.\" And so there was, creating the stars, planets, dimensions, and galaxies. Then, the first day passed, and there was the second day. Hevipelle said, \"Seperate the normal dimensions and infinity dimensions from each other, and let there be tickspeed upgrades, to measure the time.\" So the normal dimensions and infinity dimensions were seperated, and there were tickspeed upgrades. Then Hevipelle said, \"Let there be eternity points to sew the fabric of time together, and let there be time studies and time theorems, to let humanity progress.\" And so there were eternity points, time theorems, and time stuides. Then, the second day passed and the third day began. \"Let there be life,\" Hevipelle said, creating humanity and other intelligent species. Then, he said, \"Let there be Time Dimensions, and let them be a different dimension than the others.\" And so there were time dimensions, speeding up tickspeed upgrades. Then Hevipelle snapped his fingers and created a computer. \"With this, I will be able to update my universe,\" he said. But as he was working on making break_infinity.js up to 1e1e1e308 instead of 1e1e308, a rift opened to the 9th dimension, and the serpent Slabdrill, the lord of all Unhevi, slithered out. \"I will cause an apocalypse for humanity with Cancer mode,\" Slabdrill said. And so, the world became imperfect, leading to war. If only there was OmegaNum.js...", true, "am74"],
["If you find cancer in your computer, please call 119", true, "am75"],
["Breaking news! News is broken!", true, "am76"],
["There are a lot of news tickers, how did you find this one?", true, "am77"],
["The universe should have been destroyed long ago and is somehow still here", true, "am79"],
["Skididdle skidadder, you are now antimatter", true, "am80"],
["Onion", true, "am82"],
["Onion^2", "player.newsArray.includes('am82')", "am83"],
["Onion^Onion", "player.newsArray.includes('am83')", "am84"],
["It seems that an upcoming AD mod will have more onions than antimatter", "player.newsArray.includes('am84')", "am85"],
["The uprising of the onion is a compelling feat, that our scientists are experimenting on how the onion behaves as a term for a number. These onions somehow have the capability to surpass numbers beyond antimatter. We don't know why, or how.", "player.newsArray.includes('am85')", "am86"],
["We have reached Onion^^Onion, we have no idea how it happened, and all we know that it seems to be increasing at an ever-faster rate. It's Onion^^^Onion now and it's definitely larger than our antimatter amount. Oniologists have been studying these recent growth of onions and have yet to come to a conclusion on how these onions are growing so fast. Judging by the current rate of growth, it has been predicted by oniologists that the entire multiverse would be completely filled to the brim with onions by 2020.", "player.newsArray.includes('am86')", "am87"],
["Onionify: Coming in 2020 to NG+3. Make onions dominate null matter with this prestige layer!", "player.newsArray.includes('am85')", "am88"],
["Can an antimatter can can a can of antimatter can all full of antimatter food that can destroy a can made out of antiantimatter?", true, "am92"],
["If Aarexese in Aarexese is English, then is English in Aarexese Aarexese?", true, "am93"],
["Aarexify is coming in an update after the next one.", true, "am94"],
["Wait, there's a co-developer?", true, "am95"],
["Having fun waiting?", true, "am96"],
["I'm done writing news for today.                                                                                                                                                         ", true, "am104"],
["Some Scientists discovered anti-null matter, which is very useful. These scientists are now the heads of all existing research programs.", true, "am108"],
["You are luck", 'Math.random() <= 1e-15', "am109"],
["I like onions, but not when they [redacted]", true, "am110"],
["I like garlic, because it allows me to have my daily intake of vitamin G.", true, "am111"],
["Florida man puts tetraethyllead in Aarex's car so he has to stay at home so he can update NG+++", true, "am112"],
["Florida man attempts the Unscaled Incremental in real life, destroys Florida", true, "am113"],,
["Whale complained he can't give Aarex money", true, "am116"],
["Meta-dimension tickspeed when?", true, "am117"],
["Waiting I see", true, "am118"],
["Don't click this news", true, "am122"],
["Antimatter has just declared war on Matter. We are no longer safe. We are no longer free.", true, "am135"],
['Wait a second. I think I\'ve realized something. The main writer never says what broadcasting channel we\'re on. I was always curious what channel our news show is on, so I went into a top secret room the main writer never tells us to go in. And what I found...I found what channel we broadcasted on. It is "999". But channel 999 doesn\'t exist! And I also found some other things...at the bottom-right of the page, it says "Sponsored by Hevipelle". Who is Hevipelle? I\'ve never heard anyone named Hevipelle in the world. Does this mean...does this mean that Hevipelle is a nickname for someone? A...oh no. There\'s more text. A sentence says...it says..."Because the physics of the game "Antimatter Dimensions" does not allow for visuals, all thoughts, feelings, and actions made by any being are put into short news tickers. OH MY GOD I\'M IN A VIDEOGAME OH GOD THIS IS A NEWS TICKER F\*\*\* THIS DEVELOP-sifdweyfwytrwqe8723648765237869iyusdqwe-0))$#(&)QBTR&_(B)&30-b5q&)rfb)+B0R-98w#$)9b)({bew)#(5R[q)(t()qet){(q#*bT8bb &){rb&rqw#b %&r7#w&R&{07&&b#w$&b )r ({e[-(b reafbgu ({brdiuufertuyreuyyuyuefuyuyfiYUiuyEYUFiuyGUY087378578052}}}}}}},,,', true , "am144"],
["Hi, Billy Mays here for the Unscaled Incremental game, the new easier way to waste time!", true, "am145"],
["When does the 0th dimension come out", true, "am146"],
["I was stuck in a grinding section. Thanks to gods, I can finally get out of here.", false, "am148"],
['"New game dammit" - GrayStillPlays', true, "am153"],
['"More zeroes dammit" - GrayStillPlays', true, "am154"],
["i know your type. you're, uh, very determined, aren't you? you'll never give up, even if there's, uh... absolutely NO benefit to persevering whatsoever. if i can make that clear. no matter what, you'll just keep going. not out of any desire for good or evil... but just because you think you can. and because you \"can\"... ... you \"have to\". but now, you've reached the end. there is nothing left for you now. so, uh, in my personal opinion... the most \"determined\" thing you can do here? is to, uh, completely give up. and... well... do literally anything else.", true, "am155"],
/*NEXT ID: am156*/
  
//SuperSpruce's tickers
["Hi! SuperSpruce here, back with another incremental game: The Unscaled Incremental.", true, "s1"],
["'I'm bad at using glitch' -Despacit", true, "s2"],
["'Oh no! Bug!' -Despacit", true, "s3"],
["'Oh no the game broke again' -Despacit", true, "s4"],
["'A bug is when a button doesn't do anything when it should do something. A glitch is when something breaks in the game, causing funny and often useful things to happen, like Missingno in Pokemon.' -SuperSpruce", true, "s5"],
["https://www.youtube.com/channel/UCrpbLYZYpwpkrW9j9x8Ci2A/", true, "s6"],
["https://www.youtube.com/channel/UCrpbLYZYpwpkrW9j9x8Ci2A/", true, "s7"],
["https://www.youtube.com/watch?v=ub82Xb1C8os", true, "s8"],
["https://www.youtube.com/watch?v=oHg5SJYRHA0", true, "s9"],
["https://www.youtube.com/watch?v=eGHfNuzdIaE", true, "s10"],
["owo", true, "s11"],
["uwu", true, "s12"],
["A third type of matter has been discovered: null matter. It doesn't do anything and is basically useless. The scientists who discovered it were fired. Wait... it's not useless... since you can get discovery points with it, allowing you to discover more stuff!", true, "s13"],
["Did you know? This game was made to enter for a Incremental Game tournament! It came in 3rd place out of 8!", true, "s14"],
["Github > glitch", true, "s15"],
["Glitch likes to glitch", true, "s16"],
["Person A: Guys! I found out that glitch does not like to glitch! Everyone else: YAAAAYYYY!! Person A: Yeah, it likes to bug. Everyone else: WAAAA", true, "s17"],
["https://discord.gg/jeRajFK", true, "s18"],
["https://www.patreon.com/SuperSpruce", true, "s19"],
["People with @Pinglol when they get pinged: lol  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   People without @Pinglol when they get pinged: REEEEEEEEEEE", true, "s20"],
  ["'Wanna be friends?' -Tom", true, "s21"],
  ["'Wanna be friends?' -Todd", true, "s22"],
  ["'Wanna be friends?' -Call", true, "s23"],
  ["'Wanna be friends?' -Calls", true, "s24"],
  ["'Wanna be friends?' -Logan", true, "s25"],
  ["'Wanna be friends?' -Bananarama", true, "s26"],
  ["'Wanna be friends?' -A bot", true, "s27"],
  ["'Wanna be friends?' -A bot", true, "s28"],
  ["'Wanna be friends?' -A complete and utter BOT", true, "s29"],
  ["'Here before 800 subscribers. Great content! Also, i wanna be youtube friends :O' -Sounds", true, "s30"],
  ["'Loved it' -Tom", true, "s31"],
  ["'Loved it' -Todd", true, "s32"],
  ["'Loved it' -Call", true, "s33"],
  ["'Loved it' -Calls", true, "s34"],
  ["'Loved it' -Logan", true, "s35"],
  ["'Loved it' -Bananarama", true, "s36"],
  ["'Loved it' -A bot", true, "s37"],
  ["'Loved it' -A bot", true, "s38"],
  ["'Loved it' -A complete and utter BOT", true, "s39"],
  ["'Here before 800 subscribers. Great content! Also, i wanna be youtube friends :D' -A totally not suspicious bot", true, "s40"],
  ["Why did Hyp Cos, the creator of the strongest googological notation at the time, Strong Array Notation, use only the Bashicu Matrix System, the notation that dethroned his Strong Array Notation as the most powerful googological notation, in his game 'Incremental Googology'?", true, "s41"],
  ["'I think CBot has the same DNA as me, I want to marry them!' -Embi", true, "s42"],
  ["'TGM should really be running every second of every day! This is a multi-millenium scientific experiment!' -Embi", true, "s43"],
  ["'In an essay for my biology essay, I wrote a 4000 word paragraph about the percent of my DNA I got from my mom' -Embi", true, "s44"],
  ["'When do you think Username will reach (0,0,0)(1,1,1)(2,2,2)(3,3,3)(4,4,3)(4,3,1)(4,3,1)(4,3,1)(4,3,0)(5,4,1)(6,5,2)(7,6,3)(8,7,3)(6,5,2)(7,6,3)(8,7,3)(6,5,2)(7,6,3)(8,1,0)(9,2,1)(10,3,2)(11,4,3)(12,3,2)(13,4,3)(14,1,0)(15,2,1)(16,3,2)(17,4,3)(18,3,2)(19,4,3)(20,1,0)(21,2,1)(22,3,2)(23,4,3)(23,4,1)(23,4,0)(23,2,0) in his analysis??' -Embi", true, "s45"],
  ["'I am exhausted from seeing these low level expressions over and over again [he is referring to User's BMS sheet here]' -Embi", true, "s46"],
  ["'I think I want to sell Username's BMS analysis at my local bookstore so I can make money' -Embi", true, "s47"],
  ["'I will believe that I am in the +f_psi(M^M^w)(100) sigma of a SD curve' -Embi", true, "s48"],
  ["'What do you think about my plan to hack the DNA test companies to put 1/f_psi(e_(M+1))(100) as the percent of DNA I get from my mom?' -Embi", true, "s49"],
  ["'If Username doesn't reach (0,0,0)(1,1,1)(2,2,2) in his BMS analysis I will be depressed because I can't show it to my girlfriend' -Embi", true, "s50"],
  ["'We should really slow TGM down, we're going to miss so many important ordinals' -Embi", true, "s51"],
  ["'Why are my friends so dumb? It's not like they're dumb' -Embi", true, "s52"],
  ["'I think we should invent a religion based on googology' -Embi", true, "s53"],
  ["'Oh my god BMS is so (I want to vomit!!!!!!)' -Embi", true, "s54"],
  ["'Please teach students to convert between Bird's Array Notation and FGH and BMS' -Embi", true, "s55"],
  ["'I've been trying to get my classmates to analyse BMS for me, for some reason they don't listen!' -Embi", true, "s56"],
  ["'I wonder what a legion space looks like in real life, I can't even imagine an infinite-dimensional space...' -Embi", true, "s57"],
  ["'I'm getting my friend shepk to watch TGM for me when I'm asleep, so I don't miss any tetraterm decrements!' -Embi", true, "s58"],
  ["'Seriously, I really feel that we should have ONE FULL CHAPTER in math textbook specially dedicated to googology' -Embi", true, "s59"],
  ["'What do you think the chance I'll get f_psi(e_(M+1))(100) in my DNA test is?' -Embi", true, "s60"],
  ["'I will scarifice (give up) with my life . Admit that I am the most miserable psi(M^M^w)% of human beings and it is God's plan for me to die' -Embi", true, "s61"],
  ["'How much DNA do you think I inherit form my mom?' -Embi", true, "s62"],
  ["'I love to waste class time in my grammar class by writing googological terms as vocab words, so I have to explain them to my class. I think this is the best way to waste class time.' -Embi", true, "s63"],
  ["'The holy spirit in my dream told me that Username will reach psi(Ipsi_I(I)) in his BMS analysis in 2030' -Embi", true, "s64"],
  ["'Did you know I wrote (0,0,0)(1,1,1)(2,2,2)(3,3,3)(4,4,2)(5,5,1)[10^102] as an answer on one of my homework assignments for school! I'm sure my teacher will be so confused I'll get good grades!' -Embi", true, "s65"],
  ["'I should put 10000 versions of the same article on Wikipedia' -Embi", true, "s66"],
  ["'YOU KNOW, AT THIS POINT, I AM TEMPTED TO ASK MY GIRLFRIEND TO ANALYZE BMS' -Embi", true, "s67"],
  ["'I can't believe my friends are so dumb that they can't even understand up-arrow notation' -Embi", true, "s68"],
  ["Nice. This is my 69th news ticker.", true, "s69"],
  ["How does Embi even have a girlfriend?!?!?!?!?!", true, "s70"],
  ["Subscribe to SuperSpruce on YouTube!", true, "s71"],
  ["Subscribe to SuperSpruce on YouTube!", true, "s72"],
  ["Subscribe to SuperSpruce on YouTube!", true, "s73"],
  ["Subscribe to SuperSpruce on YouTube!", true, "s74"],
  ["Subscribe to DerModster on YouTube!", true, "s75"],
  ["Welcome to the unscaled incremental, the game with no cost scaling!", true, "s76"],
  ["Why does the game claim to have no cost scaling when the first discovery upgrade has exponential cost scaling?", true, "s77"],
  ["Why does the game claim to have no cost scaling when the second discovery upgrade has irregular cost scaling?", true, "s78"],
  ["Follow DerModster on Twitch!", true, "s79"],
  ["Credit to Hevipelle for the news ticker code and many of the news tickers", true, "s80"],
  ["Credit to Hevipelle for the dimension system", true, "s81"],
  ["Credit to Aarex for making some of the news tickers", true, "s82"],
  ["Credit to SuperSpruce for the game and many of the news tickers", true, "s83"],
  ["Credit to Patcail for inspiring me to make the game (for the incremental torunament)", true, "s84"],
  ["Before you ask, no, this game will not be a SuperSpruce YouTube series", true, "s85"],
  ["Results of the incremental game tournament: 8th = Color Wheels (https://dravitar.github.io/ColorWheels/), 7th = Pride and Accomplishment (https://katakana1.github.io/pride-and-accomplishment/), 6th = NUMBGER (https://yahtzeemaster26.github.io/numbger/), 5th = One Generator Infinite Upgrades (https://naruyoko.github.io/one-generator--infinite-upgrades/), 4th = Reactor Idle Knockoff 100 (https://redfire75369.github.io/Reactor-Idle-Knockoff-100/), 3rd = The Unscaled Incremental (The game you are literally playing right now, idiot), 2nd = Reinhardt's House (https://reinhardt-c.github.io/ReinHouse/), and 1st = Sushi Beans (https://sushibeans.glitch.me/). Disqualified games: http://htmlpreview.github.io/?https://github.com/dshamlin98/dshamlin98.github.io/blob/master/lngi%20UNAN.html, https://likeable-playful-skunk.glitch.me/, http://cthulhu-ai.glitch.me/, https://too-big-but-bigger.glitch.me/, https://superopgamemaker.github.io/elemental-dimensions/, and https://www.latlmes.com/world/antimatter-dimensions-reality-test-leak-1", true, "s86"],
  ["Ba ba ba baa baa ba ba baa, ba ba, ba ba ba baa baa ba ba, YEE", true, "s87"],
  ["What does RG actually stand for? Realm Grinder? Replicated Galaxy? Red-Green Gluon?", true, "s88"],
  ["'Ew mods' -Earth", true, "s89"],
  ["BREAKING NEWS: Florida man pings @punk for no reason on the vanilla Antimatter Dimensions server, Hevi catapults him into the Atlantic Ocean", true, "s90"],
  ["'Stupid SuperSpruce' -https bot", true, "s91"],
  ["'@SuperSpruce' -1e308", true, "s92"],
  ["'@everyone' -Birdbot", true, "s93"],
  ["Is this a news ticker or a new sticker?", true, "s94"],
  ["In Soviet Russia, null matter creates you", true, "s95"],
  ["Trolololololol", true, "s96"],
  ["If you thought this game was OP with the numbers, wait until you get some regular matter!", true, "s97"],
  ["This is the Knobbelboy news ticker. Only 98% of it is sho", true, "s98"],
  ["The null matter in this game is gone through special processes to become clovers in Clover Clicker, which produces flowers. Those flowers are used in my level 'Evil Flowers' in Geometry Dash.", true, "s99"],
  ["For some reason, long news tickers freeze after a while. A new one eventually appears. Nobody knows what causes this bug. Maybe you can help me figure it out and fix it!", true, "s100"],
  ["ew embi", true, "s101"],
  ["weeew is z0 get over it", true, "s102"],
  ["weeew is G0 get over it", true, "s103"],
  ["If AI-generated news tickers exist in 2020, what will AI generate by 2050?", true, "s104"],
  ["This game is better than the $60 AAA games that STILL try to manipulate you into forking over hundreds via loot boxes. How have these big-budget games become trash mobile games with better grahpics?", true, "s105"],
  ["Gameplay > Graphics", true, "s106"],
  ["Gameplay > Graphics", true, "s107"],
  ["Gameplay > Graphics, except when there's a bug that prevents you from adding more gameplay", true, "s108"],
  ["'Gameplay < Graphics' -EA", true, "s109"],
  ["If this game is feeling slow and you want some entertainment while you're waiting, either watch SuperSpruce's YouTube videos, or just watch this one: https://www.youtube.com/watch?v=YUln4BNsUIA", true, "s110"],
  ["'@Gerald' -6327", true, "s111"],
  ["'@Gerald' -6327. 'Why you ping me?' -Gerald. '@Gerald' -6327", true, "s112"],
  ["'@SuperSpruce' -a bot. 'PING' -SuperSpruce. 'What is ping, @SuperSpruce?' -the same bot", true, "s113"],
  

//luck
["This news message is 1000x rarer than all the others.", "Math.random() < 0.001", "l1"],
["You just won a small prize in the lottery.", "Math.random() < 1e-4", "l2"],
["You just won a moderate prize in the lottery.", "Math.random() < 1e-5", "l3"],
["You just won a large prize in the lottery.", "Math.random() < 1e-6", "l4"],
["You just won a huge prize in the lottery.", "Math.random() < 1e-7", "l5"],
["You just won a massive prize in the lottery.", "Math.random() < 1e-8", "l6"],
["You just won a very massive prize in the lottery.", "Math.random() < 1e-9", "l7"],
["You just won the lottery.", "Math.random() < 1e-10", "l8"],
["Just how lucky are you?", "Math.random() < 1e-11", "l9"],
["This news message is 1000000000000x rarer than all the others.", "Math.random() <= 1e-12", "l10"],
["This news message is 10x more common than all the others.", true, "l11"],
["This news message is 10x more common than all the others.", true, "l12"],
["This news message is 10x more common than all the others.", true, "l13"],
["This news message is 10x more common than all the others.", true, "l14"],
["This news message is 10x more common than all the others.", true, "l15"],
["This news message is 10x more common than all the others.", true, "l16"],
["This news message is 10x more common than all the others.", true, "l17"],
["This news message is 10x more common than all the others.", true, "l18"],
["This news message is 10x more common than all the others.", true, "l19"],
["This news message is 10x more common than all the others.", true, "l20"],
["Your Clicker Heroes mercenary lived as long as Lazeellama's Dogmeat!", "Math.random() <= 1.2e-10", "l22"],
["You tried to flirt with a cute boy/girl, and he/she didn't respond...", true, "l23"],
["You tried to flirt with a cute boy/girl, and he/she showed signs of flirting back, but quickly stopped doing that...", "Math.random() < 0.1", "l24"],
["You tried to flirt with a cute boy/girl, and he/she flirted back! However, he/she was not into you...", "Math.random() < 0.01", "l25"],
["You just asked a cute boy/girl on a date, and he/she said YES! And he/she kept on his/her promise!! However, he/she didn't like the date so he/she did not become your boyfriend/girlfriend...", "Math.random() < 5e-6", "l26"],
["You just asked a cute boy/girl on a date, and he/she said YES! However, he/she did not keep on his/her promise...", "Math.random() < 2e-3", "l27"],
["You just asked a cute boy/girl on a date, and he/she said no...", "Math.random() < 0.3", "l28"],
["You just asked a cute boy/girl on a date, and he/she said YES! And he/she kept on his/her promise!! Then he/she asked you on a second date! After several dates, you ask to be his/her girlfriend/boyfriend, and he/she says YES!!! You just got a boyfriend/girlfriend!!!", "Math.random() <= 1e-13", "l21"],
["You just asked a cute boy/girl on a date, and he/she said YES! And he/she kept on his/her promise!! Then he/she asked you on a second date! After several dates, you ask to be his/her girlfriend/boyfriend, and he/she says NO...", "Math.random() <= 5e-10", "l29"],
["You tried to flirt with a cute boy/girl, and he/she flirted back! He/she showed genuine interest in you, and after asking him/her on a date, he/she said no...", "Math.random() < 5e-4", "l30"],
["You tried to flirt with a cute boy/girl, and he/she flirted back! He/she showed genuine interest in you, and after asking him/her on a date, he/she said YES! However, he/she did not keep on his/her promise...", "Math.random() < 5e-5", "l31"],
["You tried to flirt with a cute boy/girl, and he/she flirted back! He/she showed genuine interest in you, and after asking him/her on a date, he/she said YES! And he/she kept on his/her promise!! However, he/she didn't like the date so he/she did not become your boyfriend/girlfriend...", "Math.random() < 2e-6", "l32"],
["You tried to flirt with a cute boy/girl, and he/she flirted back! He/she showed genuine interest in you, and after asking him/her on a date, he/she said YES! And he/she kept on his/her promise!! Then he/she asked you on a second date! After several dates, you ask to be his/her girlfriend/boyfriend, and he/she says NO...", "Math.random() <= 2e-10", "l33"],
["You tried to flirt with a cute boy/girl, and he/she flirted back! He/she showed genuine interest in you, and after asking him/her on a date, he/she said YES! And he/she kept on his/her promise!! Then he/she asked you on a second date! After several dates, you ask to be his/her girlfriend/boyfriend, and he/she says YES!!! You just got a boyfriend/girlfriend!!!", "Math.random() <= 1e-13", "l34"],
["A boy/girl is crushing on you!! But for whatever reason, you don't think he/she is very cute, so the spark never happens... If only your brain was wired a little differently, you could've got a boyfriend/girlfriend...", "Math.random() <= 5e-11", "l35"],
["A boy/girl is crushing on you!! And you think he/she is cute, leading you to ask him/her on a date! He/she says YES! Then he/she asked you on a second date! After several dates, you ask to be his/her girlfriend/boyfriend, and he/she says YES!!! You just got a boyfriend/girlfriend!!!", "Math.random() <= 5e-14", "l36"],
  
  // Patreon ones
["Is this a jojo reference?", true, "pat1"]
];}

var s = document.getElementById('news');
document.addEventListener("visibilitychange", function() {if (!document.hidden) {scrollNextMessage();}}, false);
var scrollTimeouts = [];
var nextMsgIndex;
function scrollNextMessage() {
  //don't run if hidden to save performance
  updateNewsArray();
  //select a message at random

  try {
    do {nextMsgIndex = Math.floor(Math.random() * newsArray.length)} while (!eval(newsArray[nextMsgIndex][1]))
  } catch(e) {
      console.log("Newsarray doesn't work at idx " + nextMsgIndex)
  }

  scrollTimeouts.forEach(function(v) {clearTimeout(v);});
  scrollTimeouts = [];

  //set the text
  s.textContent = newsArray[nextMsgIndex][0];

  //get the parent width so we can start the message beyond it
  let parentWidth = s.parentElement.clientWidth;

  //set the transition to blank so the move happens immediately
  s.style.transition = '';
  //move div_text to the right, beyond the edge of the div_container
  s.style.transform = 'translateX('+parentWidth+'px)';

  //we need to use a setTimeout here to allow the browser time to move the div_text before we start the scrolling
  scrollTimeouts.push(setTimeout( function() {
    //distance to travel is s.parentElement.clientWidth + s.clientWidth + parent padding
    //we want to travel at rate pixels per second so we need to travel for (distance / rate) seconds
    let dist = s.parentElement.clientWidth + s.clientWidth + 60;//20 is div_container padding
    let rate = 160; //change this value to change the scroll speed
    let transformDuration = dist / rate;


    //set the transition duration
    s.style.transition = 'transform '+transformDuration+'s linear';
    let textWidth = s.clientWidth;
    //we need to move it to -(width+parent padding) before it won't be visible
    s.style.transform = 'translateX(-'+(textWidth+5)+'px)';
    //automatically start the next message scrolling after this one finishes
    //you could add more time to this timeout if you wanted to have some time between messages
    // tl;dr: if length of news ticker is over 50, make it take twice as long for the next ticker to come
    scrollTimeouts.push(setTimeout(scrollNextMessage, Math.ceil(9000 + transformDuration * (newsArray[nextMsgIndex][0].length * 5))));
  }, 100));
}
